[2024-06-20 02:35:57,760] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T02:35:44.780468+00:00 [queued]>
[2024-06-20 02:35:57,782] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T02:35:44.780468+00:00 [queued]>
[2024-06-20 02:35:57,783] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 02:35:57,784] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-20 02:35:57,784] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 02:35:57,814] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_mail> on 2024-06-19 02:35:44.780468+00:00
[2024-06-20 02:35:57,823] {standard_task_runner.py:52} INFO - Started process 3339 to run task
[2024-06-20 02:35:57,827] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'desafio3_pipeline', 'send_mail', 'scheduled__2024-06-19T02:35:44.780468+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpjeaklgu7', '--error-file', '/tmp/tmpp977gxvz']
[2024-06-20 02:35:57,829] {standard_task_runner.py:80} INFO - Job 28: Subtask send_mail
[2024-06-20 02:35:57,933] {task_command.py:371} INFO - Running <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T02:35:44.780468+00:00 [running]> on host 3f4d47b0555b
[2024-06-20 02:35:58,049] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=desafio3_pipeline
AIRFLOW_CTX_TASK_ID=send_mail
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T02:35:44.780468+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-19T02:35:44.780468+00:00
[2024-06-20 02:36:00,031] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d2e1a72fcca58-705ccb3bedbsm11293779b3a.120 - gsmtp')
[2024-06-20 02:36:00,032] {logging_mixin.py:115} INFO - El email no se pudo enviar.
[2024-06-20 02:36:00,032] {python.py:173} INFO - Done. Returned value was: None
[2024-06-20 02:36:00,061] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=desafio3_pipeline, task_id=send_mail, execution_date=20240619T023544, start_date=20240620T023557, end_date=20240620T023600
[2024-06-20 02:36:00,130] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-06-20 02:36:00,185] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
